### ISSUE TITLE
Add option to follow a fork

### ISSUE THREAD

**Issue by davedelong** [kiliankoe/swift-outdated#44]
Some of the dependencies in my project are a fork of another project. It would be very neat to have an option that would allow me to follow a fork when determining outdatedness.

**Comment by kiliankoe** [comment]
Also been a while here, but `swift-outdated` finally supports this as well now! It's a bit tricky since I don't want to limit this to only GitHub repos (for autodiscovering forks through the API) or requiring users to specify this with a CLI flag every time. So it boils down to an optional config file:

```yaml
forks:
  - fork: https://github.com/mycompany/SomeLib.git
    upstream: https://github.com/original/SomeLib.git
```

At least this kinda makes it easier to point others at the canonical upstream as well I guess 🤷
